version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - run:
          name: Install dependencies (debian)
          command: |
            sudo apt-get update
            sudo apt-get install gcc gfortran make binutils binutils-dev libc6-dev libbsd-dev 
            sudo apt-get install libnetcdf-dev libhdf5-dev
            sudo apt-get install colorize
            sudo apt-get install cdo
            sudo apt-get install rake ruby3.1-dev
      - run:
          name: Install dependencies (testing)
          command: |
            pip install xarray netcdf4 six numpy unittest2
            gem install parallel --version '<= 1.12' --user -N
            gem install minitest colorize facets --user -N
            gem install narray --user -N
            gem install narray_miss --user -N
            gem install ruby-netcdf --user -N
      - run:
          name: Checkout cdo-bindings
          command: |
            git clone -b ${CIRCLE_BRANCH} https://github.com/Try2Code/cdo-bindings.git
      - run:
          name: Run Tests Python 3.9
          command: |
            cdo -V
            type -p cdo
            python3 --version
            cd cdo-bindings
            rake testPython3 CDO=$(type -p cdo) NO_COLOR=1
      - run:
          name: Run Tests Python 3.9 - no netCDF4/Xarray
          command: |
            cdo -V
            type -p cdo
            python3 --version
            cd cdo-bindings
            pip uninstall -y xarray netcdf4
            rake testPython3 CDO=$(type -p cdo) NO_COLOR=1
      - run:
          name: Run Tests Ruby 3.1
          command: |
            cdo -V
            type -p cdo
            ruby --version
            cd cdo-bindings
            cd ruby; ruby test/test_cdo.rb CDO=$(type -p cdo)
